# Задача 1: сравнение предложений

## 1.1. Считываем данные из файла

In [19]:
with open('sentences.txt', 'r') as file_sentences:
    data_sentences = list(file_sentences)
    str_sentences = str(data_sentences)
    print(data_sentences)

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n', 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n', 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n', 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n', 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n', 'However, if the output is piped or redirected, cat is unnecessary.\n', 'cat with one named file is safer where human

## 1.2. Разбиваем на строки

In [20]:
for line in data_sentences:
    print(line)

In comparison to dogs, cats have not undergone major changes during the domestication process.

As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.

A common interactive use of cat for a single file is to output the content of a file to standard output.

Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.

In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.

Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).

However, if the output is piped or redirected, cat is unnecessary.

cat with one named file is safer where human error is a concern - one wrong us

## 1.3. Приводим строки к нижнему регистру

In [21]:
lowercase_sentences = []
for i in range(len(data_sentences)):
    lowercase_sentences.append(data_sentences[i].lower())

In [22]:
for line in lowercase_sentences:
    print(line)

in comparison to dogs, cats have not undergone major changes during the domestication process.

as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.

a common interactive use of cat for a single file is to output the content of a file to standard output.

cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.

in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.

domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).

however, if the output is piped or redirected, cat is unnecessary.

cat with one named file is safer where human error is a concern - one wrong us

## 1.4. Разбиваем текст на слова (токенизация)

In [23]:
import re

words_sentences = []
for line in lowercase_sentences:
    words_sentences.append(re.split('[^a-z]', line))

for line in words_sentences:
    print(line)

['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', '']
['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', '']
['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', '']
['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', '', '']
['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', '', '']
['the', 'domesticated', 'cat', 'and', 'its', 'closest

## 1.5. Чистим от пробелов

In [24]:
clean_sentences = [[] for i in range(len(words_sentences))]

i = 0
for line in words_sentences:
    for words in line:
        if words != '':
            clean_sentences[i].append(words)
    i = i + 1

In [25]:
for line in clean_sentences:
    print(line)

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process']
['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes']
['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output']
['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals']
['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin']
['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 't

## 1.6. Составляем список всех слов

In [26]:
dict_sentences = {}

i = 0
for line in clean_sentences:
    for words in line:
        if words not in dict_sentences:
            dict_sentences[words] = i 
            i += 1
            
for item in dict_sentences:
    print (item, ': ', dict_sentences[item])

in :  0
comparison :  1
to :  2
dogs :  3
cats :  4
have :  5
not :  6
undergone :  7
major :  8
changes :  9
during :  10
the :  11
domestication :  12
process :  13
as :  14
cat :  15
simply :  16
catenates :  17
streams :  18
of :  19
bytes :  20
it :  21
can :  22
be :  23
also :  24
used :  25
concatenate :  26
binary :  27
files :  28
where :  29
will :  30
just :  31
sequence :  32
a :  33
common :  34
interactive :  35
use :  36
for :  37
single :  38
file :  39
is :  40
output :  41
content :  42
standard :  43
hear :  44
sounds :  45
too :  46
faint :  47
or :  48
high :  49
frequency :  50
human :  51
ears :  52
such :  53
those :  54
made :  55
by :  56
mice :  57
and :  58
other :  59
small :  60
animals :  61
one :  62
people :  63
deliberately :  64
tamed :  65
artificial :  66
selection :  67
they :  68
were :  69
useful :  70
predators :  71
vermin :  72
domesticated :  73
its :  74
closest :  75
wild :  76
ancestor :  77
are :  78
both :  79
diploid :  80
organisms : 

In [27]:
#d - число различных слов в предложениях

d = len(clean_sentences)
print(d)

22


In [28]:
#Посмотрим сколько у нас всего слов
n = len(dict_sentences)
print (n)

254


In [29]:
#Посмотрим что это за слова
print (dict_sentences.keys())

dict_keys(['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'concatenate', 'binary', 'files', 'where', 'will', 'just', 'sequence', 'a', 'common', 'interactive', 'use', 'for', 'single', 'file', 'is', 'output', 'content', 'standard', 'hear', 'sounds', 'too', 'faint', 'or', 'high', 'frequency', 'human', 'ears', 'such', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'one', 'people', 'deliberately', 'tamed', 'artificial', 'selection', 'they', 'were', 'useful', 'predators', 'vermin', 'domesticated', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that', 'possess', 'chromosomes', 'roughly', 'genes', 'domestic', 'similar', 'size', 'members', 'genus', 'felis', 'typically', 'weighing', 'between', 'kg', 'lb', 'however', 'if', 'piped', 'redirected', 'unnecessary', 'wit

## 1.7. Создаем матрицу

In [30]:
import numpy as np

n = len(dict_sentences)
matrix = np.zeros((n, d))
        
print (matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
#Посмотрим какого размера матрица должна быть
import pandas as pd
sentences_frame = pd.DataFrame(dict_sentences, range(len(clean_sentences)))
rows_count, columns_count = sentences_frame.shape
print (rows_count, columns_count)

22 254


In [35]:
#Создаем пустую матрицу размером n * d
#Где n - число предложений, а d - число различных слов в предложениях

for i in range(rows_count):
    for j in range(columns_count):
        sentences_frame.iloc[i,j] = 0
        
sentences_frame

in  comparison  to  dogs  cats  have  not  undergone  major  changes  \
0    0           0   0     0     0     0    0          0      0        0   
1    0           0   0     0     0     0    0          0      0        0   
2    0           0   0     0     0     0    0          0      0        0   
3    0           0   0     0     0     0    0          0      0        0   
4    0           0   0     0     0     0    0          0      0        0   
5    0           0   0     0     0     0    0          0      0        0   
6    0           0   0     0     0     0    0          0      0        0   
7    0           0   0     0     0     0    0          0      0        0   
8    0           0   0     0     0     0    0          0      0        0   
9    0           0   0     0     0     0    0          0      0        0   
10   0           0   0     0     0     0    0          0      0        0   
11   0           0   0     0     0     0    0          0      0        0   
12   0           0   0     0     0     0    0          0      0        0   
13   0           0   0     0     0     0    0          0      0        0   
14   0           0   0     0     0     0    0          0      0        0   
15   0           0   0     0     0     0    0          0      0        0   
16   0           0   0     0     0     0    0          0      0        0   
17   0           0   0     0     0     0    0          0      0        0   
18   0           0   0     0     0     0    0          0      0        0   
19   0           0   0     0     0     0    0          0      0        0   
20   0           0   0     0     0     0    0          0      0        0   
21   0           0   0     0     0     0    0          0      0        0   

    ...    disk  run  off  external  drive  fifth  update  features  more  \
0   ...       0    0    0         0      0      0       0         0     0   
1   ...       0    0    0         0      0      0       0         0     0   
2   ...       0    0    0         0      0      0       0         0     0   
3   ...       0    0    0         0      0      0       0         0     0   
4   ...       0    0    0         0      0      0       0         0     0   
5   ...       0    0    0         0      0      0       0         0     0   
6   ...       0    0    0         0      0      0       0         0     0   
7   ...       0    0    0         0      0      0       0         0     0   
8   ...       0    0    0         0      0      0       0         0     0   
9   ...       0    0    0         0      0      0       0         0     0   
10  ...       0    0    0         0      0      0       0         0     0   
11  ...       0    0    0         0      0      0       0         0     0   
12  ...       0    0    0         0      0      0       0         0     0   
13  ...       0    0    0         0      0      0       0         0     0   
14  ...       0    0    0         0      0      0       0         0     0   
15  ...       0    0    0         0      0      0       0         0     0   
16  ...       0    0    0         0      0      0       0         0     0   
17  ...       0    0    0         0      0      0       0         0     0   
18  ...       0    0    0         0      0      0       0         0     0   
19  ...       0    0    0         0      0      0       0         0     0   
20  ...       0    0    0         0      0      0       0         0     0   
21  ...       0    0    0         0      0      0       0         0     0   

    count  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  
11      0  
12      0  
13      0  
14      0  
15      0  
16      0  
17      0  
18      0  
19      0  
20      0  
21      0  

[22 rows x 254 columns]

In [33]:
#Заполняем матрицу где элемент имеет индекс (i,j)
#Дает количество вхождений j-го слова в i-е предложение
for i in range(len(clean_sentences)):
    for j in clean_sentences[i]:
        sentences_frame.loc[i, j] += 1
        
sentences_frame

in  comparison  to  dogs  cats  have  not  undergone  major  changes  \
0    1           1   1     1     1     1    1          1      1        1   
1    0           0   1     0     0     0    0          0      0        0   
2    0           0   2     0     0     0    0          0      0        0   
3    1           0   0     0     1     0    0          0      0        0   
4    2           0   0     0     1     0    0          0      0        0   
5    0           0   0     0     0     0    0          0      0        0   
6    1           0   1     0     1     0    0          0      0        0   
7    0           0   0     0     0     0    0          0      0        0   
8    0           0   1     0     0     0    0          0      0        0   
9    1           0   1     0     0     0    0          0      0        0   
10   1           0   0     0     0     0    0          0      0        0   
11   0           0   1     0     0     0    0          0      0        0   
12   1           0   0     0     0     0    0          0      0        0   
13   1           0   0     0     0     0    0          0      0        0   
14   0           0   1     0     0     0    0          0      0        1   
15   0           0   0     0     0     1    0          0      0        0   
16   1           0   2     0     0     0    0          0      0        0   
17   0           0   1     0     0     0    0          0      0        0   
18   0           0   0     0     0     0    0          0      0        0   
19   0           0   0     0     0     0    0          0      0        0   
20   1           0   1     0     0     0    0          0      0        0   
21   0           0   1     0     0     0    0          0      1        0   

    ...    disk  run  off  external  drive  fifth  update  features  more  \
0   ...       0    0    0         0      0      0       0         0     0   
1   ...       0    0    0         0      0      0       0         0     0   
2   ...       0    0    0         0      0      0       0         0     0   
3   ...       0    0    0         0      0      0       0         0     0   
4   ...       0    0    0         0      0      0       0         0     0   
5   ...       0    0    0         0      0      0       0         0     0   
6   ...       0    0    0         0      0      0       0         0     0   
7   ...       0    0    0         0      0      0       0         0     0   
8   ...       0    0    0         0      0      0       0         0     0   
9   ...       0    0    0         0      0      0       0         0     0   
10  ...       0    0    0         0      0      0       0         0     0   
11  ...       0    0    0         0      0      0       0         0     0   
12  ...       0    0    0         0      0      0       0         0     0   
13  ...       0    0    0         0      0      0       0         0     0   
14  ...       0    0    0         0      0      0       0         0     0   
15  ...       0    0    0         0      0      0       0         0     0   
16  ...       0    0    0         0      0      0       0         0     0   
17  ...       0    0    0         0      0      0       0         0     0   
18  ...       0    0    0         0      0      0       0         0     0   
19  ...       0    0    0         0      0      0       0         0     0   
20  ...       1    1    1         1      1      0       0         0     0   
21  ...       0    0    0         0      0      1       1         1     1   

    count  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  
11      0  
12      0  
13      0  
14      0  
15      0  
16      0  
17      0  
18      0  
19      0  
20      0  
21      1  

[22 rows x 254 columns]

## 1.7. Находим косинусное растояние  от предложения в самой первой строке до всех остальных

In [50]:
from scipy.spatial.distance import cosine

In [51]:
distance_from_first_sentence = []

for i in range(rows_count):
    distance_from_first_sentence.append(cosine(sentences_frame.loc[0], sentences_frame.iloc[i]))
    
print (distance_from_first_sentence)

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
